#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --mem=80G
#SBATCH --mail-type=ALL
#SBATCH --mail-user=rmohn@mortonarb.org
#SBATCH --time=1-00:00:00


module load VCFtools
module load R
cd /cwork/ram163/sweepfinder/
csomes=("Chr01" "Chr02" "Chr03" "Chr04" "Chr05" "Chr06" "Chr07" "Chr08" "Chr09" "Chr10" "Chr11" "Chr12")
#csomes1=("Chr03" "Chr04" "Chr05" "Chr06" "Chr07" "Chr08" "Chr09" "Chr10" "Chr11" "Chr12")
#csomes2=("Chr01" "Chr02")
for f in /cwork/ram163/sweepfinder/mac_IN*.pop.L
	do
	samp="$(basename ${f} .pop.L)"
		#dos2unix -n ${f} ${samp}.pop.L
	for j in ${csomes[@]}
		do
#		vcftools --gzvcf /hpc/group/manoslab/QMACROCARPA_GENOMES/24_VARIANTS_MACROCARPA/MAC99_MACREF_HQSNP2.vcf.gz --keep ${samp}.pop.L --max-missing 1 --min-alleles 2 --max-alleles 2 --remove-indels --counts2 --chr ${j} --out ${samp}.${j} --temp /scratch
		Rscript /hpc/group/manoslab/QMACROCARPA_GENOMES/SCRIPTS/20_ToMACROCARPA/sweepfinder/sweepformat.R ${samp}.${j}.frq.count
#		SweepFinder2 -sg 2000 ${samp}.${j}.alfreq ${samp}.${j}.sf2
	done
#	for k in ${csomes2[@]}
#		do#
#		Rscript /hpc/group/manoslab/QMACROCARPA_GENOMES/SCRIPTS/20_ToMACROCARPA/sweepfinder/sweepformat.R ${samp}.${k}.frq.count
		#vcftools --gzvcf /hpc/group/manoslab/QMACROCARPA_GENOMES/24_VARIANTS_MACROCARPA/MAC99_MACREF_HQSNP2.vcf.gz --keep ${samp}.pop.L --max-missing 1 --min-alleles 2 --max-alleles 2 --remove-indels --counts2 --chr ${j} --out ${samp}.${j} --temp /scratch
#		SweepFinder2 -sg 2000 ${samp}.${k}.alfreq ${samp}.${k}.sf2
#	done
#	less ${samp}.Chr*.alfreq > ${samp}.all.alfreq
#	SweepFinder2 -f ${samp}.all.alfreq ${samp}.all.pcf
#	for i in ${csomes[@]}
#		do
#		SweepFinder2 -lg 2000 ${samp}.${i}.alfreq ${samp}.all.pcf ${samp}.${i}.pcf.sf2
#	done
done

