#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --mem=30G
#SBATCH -c 20
#SBATCH --mail-type=ALL
#SBATCH --mail-user=rmohn@mortonarb.org
#SBATCH -e slurm_%A_%a.err
#SBATCH -o slurm_%A_%a.out
#SBATCH --array=1-6



##module load bcftools
##module load VCFtools
##vcftools --gzvcf /cwork/ram163/OAK_GENOMES/14_MAPPING/03_CALLED/ALL_LIST.gvcf.gz --keep /hpc/group/manoslab/QMACROCARPA_GENOMES/00a_SUBSETS/MacSamples60.txt --max-alleles 2 --max-missing 0.80 --remove-indels --thin 10000 --plink --out /cwork/ram163/OAK_GENOMES/14_MAPPING/03_CALLED/Mac60_FILTER10000 --temp /scratch
##plink --file /cwork/ram163/OAK_GENOMES/14_MAPPING/03_CALLED/Mac60_FILTER10000 --recode12 --out /cwork/ram163/OAK_GENOMES/14_MAPPING/03_CALLED/Mac60_FILTER10000
admixture --cv /cwork/ram163/OAK_GENOMES/14_MAPPING/03_CALLED/Mac60_FILTER10000.ped ${SLURM_ARRAY_TASK_ID} -j20 | tee log_Mac60FILTER_S${SLURM_ARRAY_TASK_ID}.out
